trigger:
  branches:
    include:
      - main

pool:
  name: Enterprise-AKS-Agents

variables:
- group: Enterprise-AKS-Variables

stages:

- stage: Build

  displayName: Build Docker Image

  jobs:

  - job: DockerBuild

    displayName: Build & Push Image

    steps:

    - checkout: self

    - template: templates/docker-build.yml

      parameters:

        acrServiceConnection: 'ACR-ServiceConnection'

        imageRepository: 'enterprise-flask'

        dockerfile: 'application/Dockerfile'

        buildContext: 'application'

    - task: CopyFiles@2

      displayName: Copy Kubernetes Manifests

      inputs:
        SourceFolder: application/k8s
        Contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - task: PublishBuildArtifacts@1

      displayName: Publish K8s Manifests

      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: manifests

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  condition: succeeded()
    
  jobs:

  - job: Deploy

    displayName: Kubernetes Deployment

    steps:

    - download: current

      artifact: manifests

    - template: templates/deploy-aks.yml

      parameters:

        azureSubscription: 'Azure-ServiceConnection'

        resourceGroup: 'prod-aks-rg'

        aksCluster: 'prod-aks'