apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-kv

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "37c7330a-8d4c-4665-b609-55a7f34a045d"
    keyvaultName: "prodkvdeb2026"

    cloudName: ""
    tenantId: "b24e2927-f763-4eda-b681-1f150c208e21"

    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
