apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-kv

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "prodkvdeb2026"
    tenantId: "b24e2927-f763-4eda-b681-1f150c208e21"


    objects: |
      array:
        - |
          objectName: app-secret
          objectType: secret
